## YAML Template.
---
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Laboratory
    username: nicocraxker33
    password: Nicom2004$
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect